DROP TABLE IF EXISTS JOBS_CONTROL;
CREATE TABLE JOBS_CONTROL (
   ID SERIAL PRIMARY KEY,
   PROVIDER_NAME VARCHAR(500),
   RESULTS_FORMAT VARCHAR(50),
   POLLING_FREQUENCY INTEGER,
   ROOT_URL VARCHAR(500) NOT NULL,
   URL_PARAMS VARCHAR(500) NOT NULL,
   LAST_INGEST_DATETIME TIMESTAMP
);
