DROP TABLE IF EXISTS JOBS_CONTROL;
CREATE TABLE JOBS_CONTROL (
   ID SERIAL PRIMARY KEY,
   ORGANIZATION_NAME VARCHAR(500),
   DATA_LICENSE VARCHAR(500),
   IINGESTER_DEFINITION_NAME VARCHAR(20),
   RESULTS_FORMAT VARCHAR(50),
   LOAD_FREQUENCY INTEGER,
   ROOT_URL VARCHAR(500) NOT NULL,
   URL_PARAMS VARCHAR(500) NOT NULL,
   LAST_EXECUTE_DATETIME TIMESTAMP,
   ACTIVE BOOLEAN DEFAULT TRUE,
   RECALLS_ID_PREFIX VARCHAR(10),
   MAX_PKEY_VALUE INTEGER,
   MAX_MANUFACTURER_PKEY_VALUE INTEGER
)  ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO JOBS_CONTROL  (ORGANIZATION_NAME,DATA_LICENSE,IINGESTER_DEFINITION_NAME,RESULTS_FORMAT,LOAD_FREQUENCY,ROOT_URL,URL_PARAMS,LAST_EXECUTE_DATETIME,ACTIVE,RECALLS_ID_PREFIX,MAX_PKEY_VALUE,MAX_MANUFACTURER_PKEY_VALUE)
VALUES ('CPSC','FREE','CPSC','JSON', 60, 'https://www.saferproducts.gov/RestWebServices/Recall?format=json&RecallDateStart=%datetime%','',null,true,'cpsc',0,0);
COMMIT;

DROP TABLE IF EXISTS RECALLS CASCADE;
CREATE TABLE RECALLS (
  ID VARCHAR(20) PRIMARY KEY,
  SOURCE_ORGANIZATION INTEGER REFERENCES JOBS_CONTROL(ID),
  RECALL_ID VARCHAR(100),
  RECALL_NUMBER VARCHAR(100),
  RECALL_REASON VARCHAR(2000),
  RECALL_STATUS VARCHAR(100),
  RECALL_DATE DATETIME, 
  LAST_PUBLISH_DATE DATETIME,
  RECALL_DESCRIPTION VARCHAR(2000),
  RECALL_URL VARCHAR(100),
  RECALL_CLASSIFICATION VARCHAR(50),
  RECALL_VOLUNTARY_MANDATED VARCHAR(50),
  CONSUMER_CONTACT VARCHAR(200),
  REPORTED_COMPLAINTS TEXT,
  REMEDIES TEXT,
  CREATE_DATE DATETIME DEFAULT NOW()
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS PRODUCTS CASCADE;
CREATE TABLE PRODUCTS (
   ID SERIAL PRIMARY KEY,
    RECALLS_ID VARCHAR(20) REFERENCES RECALLS(ID),
    UPCS VARCHAR(1000),
    NAME VARCHAR(100),
    DESCRIPTION VARCHAR(1000),
    MODEL VARCHAR(100),
    TYPE VARCHAR(100),
    CATEGORY_ID VARCHAR(100),
    IMAGES VARCHAR(1000),
     PRODUCT_QUANTITY VARCHAR(100),
  CREATE_DATE DATETIME DEFAULT NOW()
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS MANUFACTURERS CASCADE;
CREATE TABLE MANUFACTURERS (
   ID SERIAL PRIMARY KEY,
   RECALLS_ID VARCHAR(20) REFERENCES RECALLS(ID),
   NAME VARCHAR(100),
   COMPANY_ID VARCHAR(100),
  CREATE_DATE DATETIME DEFAULT NOW()
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS MANUFACTURERS_LOCATIONS CASCADE;
CREATE TABLE MANUFACTURERS_LOCATIONS(
   ID SERIAL PRIMARY KEY,
   MANUFACTURERS_ID INTEGER REFERENCES MANUFACTURERS(ID),
   COUNTRY VARCHAR(100),
   STATE VARCHAR(100),
   CITY VARCHAR(100),
  CREATE_DATE DATETIME DEFAULT NOW()
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS HAZARDS CASCADE;
CREATE TABLE HAZARDS (
   ID SERIAL PRIMARY KEY,
   RECALLS_ID VARCHAR(20) REFERENCES RECALLS(ID),
   HAZARD VARCHAR(1000),
   HAZARD_TYPE_ID VARCHAR(50),
  CREATE_DATE DATETIME DEFAULT NOW()
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS RETAILERS CASCADE;
CREATE TABLE RETAILERS(
   ID SERIAL PRIMARY KEY,
   RECALLS_ID VARCHAR(20) REFERENCES RECALLS(ID),
   NAME VARCHAR(100),
   COMPANY_ID VARCHAR(100),
  CREATE_DATE DATETIME DEFAULT NOW()
)ENGINE=InnoDB DEFAULT CHARSET=latin1;
